name = "eQuilibrator"
uuid = "9d196975-2c9b-462f-a3cc-8957d44b8c95"
authors = ["st elmo <stelmozors@gmail.com>", "Mirek Kratochvil <exa.exa@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1"
